loki-stack:
  test_pod:
    enabled: true
    image: bats/bats:v1.10.0
    pullPolicy: IfNotPresent

  loki:
    enabled: true
    isDefault: true
    url: http://{{(include "loki.serviceName" .)}}:{{ .Values.loki.service.port }}

  promtail:
    enabled: true
    config:
      logLevel: info
      serverPort: 3101
      clients:
        - url: http://{{ .Release.Name }}:3100/loki/api/v1/push

  # proxy is currently only used by loki test pod
  # Note: If http_proxy/https_proxy are set, then no_proxy should include the
  # loki service name, so that tests are able to communicate with the loki
  # service.
  proxy:
    http_proxy: ""
    https_proxy: ""
    no_proxy: ""
