loki:
  loki:
    image:
      repository: grafana/loki
      tag: '2.9.1'
    auth_enabled: false
    commonConfig:
      replication_factor: 1
    storage:
      type: filesystem
    # workaround to fix invalid ruler config error
    rulerConfig:
      storage:
        type: local