apiVersion: v1
kind: Secret
metadata:
  name: loki-datasource
  labels:
    grafana-datasource: "true"
  namespace: loki-stack
stringData:
  loki-datasource.yaml: |-
    apiVersion: 1
    datasources:
      - type: loki
        name: Loki
        uid: loki
        url: http://loki-stack.loki-stack:3100
        access: proxy
        editable: false