apiVersion: v1
kind: Secret
metadata:
  name: grafana-datasource
  labels:
    grafana_datasource: "1"
  namespace: loki-stack
stringData:
  loki-datasource.yaml: |-
    apiVersion: 1
    datasources:
      - type: loki
        name: Loki
        uid: loki
        url: http://loki-stack.loki-stack:3100
        access: proxy
        editable: false