apiVersion: v1
kind: Secret
metadata:
  name: grafana-datasource
  labels:
    grafana_datasource: "1"
stringData:
  loki-datasource.yaml: |-
    apiVersion: 1
    datasources:
      - type: loki
        name: Loki
        uid: loki
        url: http://loki.loki:3100
        access: proxy
        editable: false