---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-mariadb
  namespace: services
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi