longhorn:
  image:
    longhorn:
      engine:
        repository: longhornio/longhorn-engine
        tag: v1.5.1
      manager:
        repository: longhornio/longhorn-manager
        tag: v1.5.1
      ui:
        repository: longhornio/longhorn-ui
        tag: v1.5.1
      instanceManager:
        repository: longhornio/longhorn-instance-manager
        tag: v1.5.1
      shareManager:
        repository: longhornio/longhorn-share-manager
        tag: v1.5.1
      backingImageManager:
        repository: longhornio/backing-image-manager
        tag: v1.5.1
      supportBundleKit:
        repository: longhornio/support-bundle-kit
        tag: v0.0.24
    csi:
      attacher:
        repository: longhornio/csi-attacher
        tag: v4.2.0
      provisioner:
        repository: longhornio/csi-provisioner
        tag: v3.4.1
      nodeDriverRegistrar:
        repository: longhornio/csi-node-driver-registrar
        tag: v2.7.0
      resizer:
        repository: longhornio/csi-resizer
        tag: v1.7.0
      snapshotter:
        repository: longhornio/csi-snapshotter
        tag: v6.2.1
      livenessProbe:
        repository: longhornio/livenessprobe
        tag: v2.9.0
    pullPolicy: IfNotPresent

  defaultSettings:
    replicaReplenishmentWaitInterval: 3600

  longhornUI:
    replicas: 1

  longhornConversionWebhook:
    replicas: 2

  longhornAdmissionWebhook:
    replicas: 2

  longhornRecoveryBackend:
    replicas: 2