apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: unifi-poller-service-monitor
  namespace: unifi-poller
spec:
  endpoints:
    - port: http
      path: /metrics
      interval: 60s
  selector:
    matchLabels:
      app.kubernetes.io/name: unifi-poller # references the target object 