apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
  namespace: networking
data:
  config.yaml: |
    tunnel: homelab
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
      - hostname: argocd.amrap030.site
        service: https://argocd-server.argocd
        originRequest:
          noTLSVerify: true
      - hostname: uptime.amrap030.site
        service: https://uptime-kuma.monitoring
        originRequest:
          noTLSVerify: true
      - service: http_status:404