apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
data:
  config.yaml: |
    tunnel: homelab
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
      - hostname: argocd.amrap030-homelab.ml
        service: https://argocd-server.argocd
        originRequest:
          noTLSVerify: true
      - service: http_status:404