apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
  namespace: networking
data:
  config.yaml: |
    tunnel: homelab
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
      - hostname: argocd.amrap030.site
        service: https://argocd-server.argocd
        originRequest:
          noTLSVerify: true
      - hostname: uptime.amrap030.site
        service: http://uptime-kuma.monitoring:3001
        originRequest:
          noTLSVerify: true
      - hostname: vaultwarden.amrap030.site
        service: http://vaultwarden.services
        originRequest:
          noTLSVerify: true
      - hostname: photoprism.amrap030.site
        service: http://photoprism.services
        originRequest:
          noTLSVerify: true
      - hostname: paperless.amrap030.site
        service: http://paperless.services:8000
        originRequest:
          noTLSVerify: true
      - hostname: iobroker.amrap030.site
        service: http://iobroker.home:8081
        originRequest:
          noTLSVerify: true
      - hostname: auth.amrap030.site
        service: http://authelia.authelia
        originRequest:
          noTLSVerify: true
      - hostname: grafana.amrap030.site
        service: http://kube-prometheus-grafana.monitoring
        originRequest:
          noTLSVerify: true
      - hostname: truenas.amrap030.site
        service: http://192.168.1.192
        originRequest:
          noTLSVerify: true
      - hostname: paperless-webdav.amrap030.site
        service: http://192.168.1.192:8080
        originRequest:
          noTLSVerify: true
      - service: http_status:404