---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-data
  namespace: services
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: paperless
    app.kubernetes.io/name: paperless
  annotations:
    volume.beta.kubernetes.io/storage-class: "truenas-nfs"
    argocd.argoproj.io/sync-options: Delete=false
  name: paperless-media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: truenas-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: paperless
    app.kubernetes.io/name: paperless
  annotations:
    volume.beta.kubernetes.io/storage-class: "truenas-nfs"
    argocd.argoproj.io/sync-options: Delete=false
  name: paperless-consume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: truenas-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: paperless
    app.kubernetes.io/name: paperless
  annotations:
    volume.beta.kubernetes.io/storage-class: "truenas-nfs"
    argocd.argoproj.io/sync-options: Delete=false
  name: paperless-export
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: truenas-nfs