---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: paperless
    app.kubernetes.io/name: paperless
  annotations:
    volume.beta.kubernetes.io/storage-class: "truenas-nfs"
    argocd.argoproj.io/sync-options: Delete=false
  name: paperless-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: truenas-nfs