apiVersion: v1
kind: Secret
metadata:
    name: authelia-secrets
    namespace: authelia
data:
    JWT_TOKEN: ENC[AES256_GCM,data:KVo3Pe9sCsFiZyWACH1sYyUlPN6K+A7mjxHNco7ACvW8IQg9NTQbNZ5kYIQSwSUQuMC4Z+MqouKKAoMnujdYkw==,iv:3HqiD5Jp07hq4IThW3lXE+kx2MwNcrLnmjfKn/3R2Es=,tag:07joy52U2fveCNsc5QBjIw==,type:str]
    SESSION_ENCRYPTION_KEY: ENC[AES256_GCM,data:sigJk2wSPX8a8mvGZI7P3LxelBvZMBdNC6lXWsRF1vcFTBDr/8PfCYBQYBo4Nrtm2ziJiAYibHcnDIhX129ALg==,iv:Db1rWN1NWVuF3u083hrNpLbRNOxKlOKNbi8KeexJDuk=,tag:fWuMfbgO5wAnSp+v2DUSlw==,type:str]
    STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:CFdqgvvNb3dThmkdapxOOxDq3LgNftG5pQ3wNJ+ZVV7446y84Gvq7coCyS+/vymI3IPhsqdMyDG4gx3fSENctg==,iv:mZZGzV4ki8fg/rlSU2t/lhxxA+6iYLUqIZT0BVUogA4=,tag:LSyOCtADmRDvpEPjF+5GLw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u30r06zu0jacsxj3m33rqggfw49up55jm0cs4hcax0vsrq4nl34s5xpg76
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTkNZYlNjWEZDV0JuYURs
            UlBwRGNqOWlpajR5QWVpWWFqM1h5cDJEclNRClVZZEpFelJnSFBqb0V1UGtZYzFW
            REZpaWV1bUkzQnlyZDgvKzJOMVNDbG8KLS0tIE51Tzl1Vmc5bitkem9IQzZscDMz
            UXI0aHZOMkV0WXhQTHVYZUcyU1RqcHcKIvmN+mblwHLKPrHWnPakG7DBrSQLczD3
            RI3phnK5f5+qZ16KdeoaN3ia7e8k0fpPIwDlN4o4iGm+REdxn/NwPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-04T00:03:02Z"
    mac: ENC[AES256_GCM,data:wLpL98R/ciz6Xxuy22njk1bZv3Yr+K5hFdd0U829fSNIOcQTqmB562POL62CEmgZd9NNy1ZizY4wWlYlpsgurwoQbjveVPjgGihMhhLmlHkNvOK5teTgCba6Voape+jNVXmtVOKy0dGzbpEd90PVCPBvNf+cj9eERUd97pMg5is=,iv:5HjgkxX4woZKbf956qQuMUajNrwhbQxQFnKvxQZg5eo=,tag:LIbotpfx3QMWzMrdVpfbgw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
