apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
    namespace: monitoring
stringData:
    adminPassword: ENC[AES256_GCM,data:bm9gXANebsg=,iv:wu0bGGHPrVxv0A6Y64V19MbjrS0sh5Mdxfif1d5SDNM=,tag:kWB/RwiXGRoFJTp2S7YGew==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u30r06zu0jacsxj3m33rqggfw49up55jm0cs4hcax0vsrq4nl34s5xpg76
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUWGxQNi8wQVFrYUtMb0xr
            Ti9EYW9wZFNWQTE3UjNWbjFnbUtTam9MTzNFCmQ0VlcvQXNDWWpWNXZLaldQd0xv
            VkJUSHRDWngwS0EyMWF0UllQTElYMTgKLS0tIGYzWUR0akVaa1lCOVh5bU9SeHh3
            emIrbG9pbm0yQkFjL2V2RWMzTDMwTzgKQGIdAwhWiBQXIXAJ0q6acbHGsOt6O7dk
            XYxsBrPAg9Vhz/XGnIZnyMTrcay43w0799OfEPTPEIwf/kyHwDbrKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-04T23:29:19Z"
    mac: ENC[AES256_GCM,data:pBTSs7fBaD1ILol4Dj5lV5gkG62MrBjgEjXh9Gdwv8eClKbQ1LDR4NTbriZ7sx1mVKQLxMXEr/Qcaxpw/p5HDmTGKGP8eVOPKf6C14UPsPmnkdmqYnr+AdDr5phYUZcs2el+Ibb7M/8vVYGdtQu9kHiWuWYZbJ361LXN2fTBJeM=,iv:6dpvJX53Au/OkiVeNFsQhXwhUasTeE6/CcDtmpUREVs=,tag:b6kwzMbbRcRYP3aDat+b4Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
