apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
    namespace: monitoring
stringData:
    GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:78owNGqvBoo=,iv:m3FXPqQmzIzrX/JjC2TeeA1LsWC3nzU86PQPLun2dQ8=,tag:wnsPm6al0Y4rlspNhACXoA==,type:str]
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:uEFnWdGN+qw=,iv:eHVSRoIvtna+cp8bhvLCkFzuh0qgXwUNqNfIxEbgwHI=,tag:cGBlx+1iklUzGE62Ajh2Fw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u30r06zu0jacsxj3m33rqggfw49up55jm0cs4hcax0vsrq4nl34s5xpg76
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAweFg1ZCtFeGo4aGExZ0c1
            WUNaeUJlRTgxNVVZbGh3Zm5id3cyY0ZNRmlrCnBrQndlVWgrdFJHaGhqWU85YTdj
            UUZWekVjRTBsOXplUDRRWVczbG95NWsKLS0tIG5yeVhnMmkrdnN4MUU1c2VSUWZF
            N01QYnZnVlB4T0JNZDVEbWhJN1FHYUEKm7I+xfll2bVEMg6x2SXW137CDse1+oe6
            Q6t5VvS45g/FIRVW0Fpe8gxW0vFXhkKCbgBtuUrUngfTDg/j0f/b1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-04T23:04:53Z"
    mac: ENC[AES256_GCM,data:KYHipj913LOcHd0rULyXWMwN84tHd9R7bzOl7reiszOxE3Tu0eMAB8zTcLjZRO4D+pzRiIkndq9rPav46O299KesfNnjXoo5Di65xnumHl3l6mH6uLvW0X4Znz1Rwp2He2xnzmq+zb6fJsML0y0ocNOdbN23tFMd1TiQMwz4NXM=,iv:xf6mdF8uUx6Uam7zVeVEgs60EsFip8QxE0mmee0nJQQ=,tag:F5Zob/PZiM2upwU4EWjPEQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
