apiVersion: v1
kind: Secret
metadata:
    name: paperless-postgres-secrets
    namespace: services
    labels:
        app: postgres
data:
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:MBPaO8Pf4rJOBUgs,iv:aYQ/w1hQKPaFE8IWHNms/9deOO25O7Sv7d3PtLpzpLE=,tag:8R1eAu4eB7PM3jXhqqJJzw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:pSkXWXzOIJRbXvPU,iv:xvb2+JEvAjVXtV7/rMQf4yWMA3yeJm6Lvj+EaXXLD5o=,tag:ZTcV4I/+4uxmU0h6h0XHlw==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:oG3VQYw2raEpGOe1ACmqgA==,iv:1Dcr3Pdlf7+PcAKElFGVkR9CDXcySwfxdfQ93xlQJZk=,tag:HxxzA4M0gvwpjZDUCKBwnQ==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u30r06zu0jacsxj3m33rqggfw49up55jm0cs4hcax0vsrq4nl34s5xpg76
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuK3U2RWZVdXpXVTBvWGZl
            Qm9hVmVzTFN3WURlL3REdGhRRXpaRVc3b0FVCmxRSTBGejh6enluMHpYa2prb1lZ
            dCtPVjNLbHRtVTUzbnNzZHZSMGJlNjgKLS0tIE9aaUwvcnVvcGhwcERVQ1ZJRytS
            NE9hRUl5dElwcG90YkdhQ1RIUXppKzAKTYOByPSZIUkWPw56bsHAL0iIthmA8gxk
            OuqoxxvnTC5MyH3p6PmibY3u0pvrrw4ryu7HF953clCEMkirHDFu6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-08T14:28:31Z"
    mac: ENC[AES256_GCM,data:fgcCAPIm4QSmGMWw0UMr8iquWuObVos0G0cXwueekxM7qT3s9OBAiCJRDx5yPWr5O5cuy1ysR/afc+dXGgtZ1s20aMrQBeJUzZlhi3H2hcHmNpuAT0TaSF9G5Asj+stUKX1awXypdqH3f1N+EssJ++j3/mUC9yFbZRZF+QJ+oko=,iv:XiPmo2YmYqeH4KZfJI51vm+4GgAa6cigZ5IwRY8akjA=,tag:nHY28Vs3FaoCtWnSYba2WA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
