apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: secret-generator
files:
  - ./ca-secret.sops.yaml
  - ./cloudflared/cloudflared-secret.sops.yaml
  - ./vaultwarden/secrets.sops.yaml
  - ./photoprism/photoprism-mariadb-secrets.sops.yaml
  - ./photoprism/photoprism-secret.sops.yaml
  - ./paperless/paperless-postgres-secrets.sops.yaml
  - ./authelia/authelia-secrets.sops.yaml
  - ./authelia/authelia-users.sops.yaml
  - ./authelia/authelia-oidc.sops.yaml
  - ./grafana/grafana-secret.sops.yaml
