apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-configmap
  namespace: authelia
data:
  configuration.yaml: |
    users:
      amrap030:
        email: kevin.hertwig@gmail.com
        password: "$argon2id$v=19$m=65536,t=3,p=4$TlrKmkl8An/mtKuJCYuzxA$FLmE8gy0dar7YMmEotaQYUfqMad0jGBkV2wo1bZC7fg"
        groups:
          - admins
          - family