apiVersion: apps/v1
kind: Deployment
metadata:
  name: iobroker
  namespace: home
  labels:
    app.kubernetes.io/instance: iobroker
    app.kubernetes.io/name: iobroker
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: iobroker-iobroker
      app.kubernetes.io/name: iobroker
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: iobroker-iobroker
        app.kubernetes.io/name: iobroker
    spec:
      hostNetwork: true 
      nodeSelector:
        kubernetes.io/hostname: k3s-w01
      containers:
      - name: iobroker
        image: buanet/iobroker:v8.1.0
        env:
          - name: USBDEVICES
            value: "/dev/ttyACM0"
        securityContext:
          privileged: true
        volumeMounts:
        - name: iobroker-data
          mountPath: /opt/iobroker
      volumes:
      - name: iobroker-data
        persistentVolumeClaim:
          claimName: iobroker-data