apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iobroker-data
  namespace: home
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
  labels:
    app: iobroker
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi