uptime-kuma:
  image:
    repository: louislam/uptime-kuma
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.23.2-alpine"

  volume:
    enabled: true
    # accessMode: ReadWriteOnce
    # size: 4Gi
    # If you want to use a storage class other than the default, uncomment this
    # line and define the storage class name
    # storageClassName:
    # Reuse your own pre-existing PVC.
    existingClaim: "uptime-kuma-data"