---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless-mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      enableServiceLinks: false
      containers:
      - image: postgres
        name: postgres
        # args:
        #   - --lower-case-table-names=1
        #   - --transaction-isolation=READ-COMMITTED
        #   - --character-set-server=utf8mb4
        #   - --collation-server=utf8mb4_unicode_ci
        #   - --max-connections=512
        #   - --innodb-rollback-on-timeout=OFF
        #   - --innodb-lock-wait-timeout=120
        #   - --innodb-buffer-pool-size=1G
        #   - --innodb_log_file_size=256M
        envFrom:
          - secretRef:
              name: paperless-mariadb-secrets
        env:
          - name: POSTGRES_DB
            value: paperless
          - name: POSTGRES_USER
            value: paperless

        resources:
          limits:
            memory: 2Gi
          requests:
            memory: 1Gi

        ports:
          - containerPort: 3306
            name: mariadb

        volumeMounts:
          - name: paperless-mariadb
            mountPath: /var/lib/mysql
            
      volumes:
        - name: paperless-mariadb
          persistentVolumeClaim:
            claimName: paperless-mariadb