---
# Kubernetes API version
apiVersion: apps/v1
# Deployment object
kind: Deployment
metadata:
  # The name of the Deployment
  name: paperless-postgres
spec:
  # Replicas for this Deployment
  replicas: 1
  selector:
    # labels the pods
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        # The label the pods created from the pod template should have
        app: postgres
    spec:
      containers:
        # The container name to execute pods
        - name: postgres
          # pull postgresimage from docker hub
          image: postgres
          ports:
            # Assign ports to expose container
            - containerPort: 5432
          envFrom:
          - secretRef:
              name: paperless-postgres-secrets
          env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          volumeMounts:
            # The volume mounts  for the container
            - mountPath: /var/lib/postgres/data
              name: paperless-postgres
      # Volumes attached to the pod
      volumes:
        - name: paperless-postgres
          persistentVolumeClaim:
            # reference the PersistentVolumeClaim
            claimName: paperless-postgres