---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless-mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      enableServiceLinks: false
      containers:
      - image: mariadb
        name: mariadb
        args:
          - --lower-case-table-names=1
          - --transaction-isolation=READ-COMMITTED
          - --character-set-server=utf8mb4
          - --collation-server=utf8mb4_unicode_ci
          - --max-connections=512
          - --innodb-rollback-on-timeout=OFF
          - --innodb-lock-wait-timeout=120
          - --innodb-buffer-pool-size=1G
          - --innodb_log_file_size=256M
          - --ignore-db-dir=lost+found
        envFrom:
          - secretRef:
              name: paperless-mariadb-secrets
        env:
          - name: MARIADB_DATABASE
            value: "paperless"
          - name: MARIADB_USER
            value: "paperless"
          - name: MARIADB_TCP_PORT
            value: "3307"
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
        resources:
          limits:
            memory: 2Gi
          requests:
            memory: 1Gi
        ports:
          - containerPort: 3307
            name: mariadb
        volumeMounts:
          - name: paperless-mariadb
            mountPath: /var/lib/mysql 
      volumes:
        - name: paperless-mariadb
          persistentVolumeClaim:
            claimName: paperless-mariadb