---
apiVersion: v1
kind: Service
metadata:
  name: paperless-postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - name: paperless-port
      protocol: TCP
      port: 5432
      targetPort: 5432