---
apiVersion: v1
kind: Service
metadata:
  name: paperless-mariadb
spec:
  type: ClusterIP
  selector:
    app: mariadb
  type: ClusterIP
  ports:
    - name: redis-port
      protocol: TCP
      port: 3306
      targetPort: 3306