---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless
  labels:
    app: paperless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paperless
  template:
    metadata:
      labels:
        app: paperless
    spec:
      enableServiceLinks: false
      containers:
        - name: webserver
          image: ghcr.io/paperless-ngx/paperless-ngx:latest
          imagePullPolicy: IfNotPresent
          # envFrom:
          # - secretRef:
          #     name: paperless-mariadb-secrets
          env:
            - name: PAPERLESS_REDIS
              value: "redis://redis-server:6379"
            # - name: PAPERLESS_DBENGINE
            #   value: "mariadb"
            # - name: PAPERLESS_PORT
            #   value: "8000" 
            # - name: PAPERLESS_DBHOST
            #   value: "paperless-mariadb"  
            # - name: PAPERLESS_DBNAME
            #   value: "paperless"
            # - name: PAPERLESS_DBUSER
            #   value: "paperless"
            # - name: PAPERLESS_DBPORT
            #   value: "3306"
            - name: PAPERLESS_URL
              value: "https://paperless.amrap030.site" 
            - name: PAPERLESS_ADMIN_USER
              value: "amrap030" 
            - name: PAPERLESS_ADMIN_PASSWORD
              value: "password" 
            - name: PAPERLESS_OCR_LANGUAGE
              value: "deu+eng"
            - name: PAPERLESS_TIME_ZONE
              value: "Europe/Berlin"
            - name: PAPERLESS_CSRF_TRUSTED_ORIGINS
              value: "https://paperless.amrap030.home,https://paperless.amrap030.site"  
            # - name: USERMAP_UID
            #   value: "1000"
            # - name: USERMAP_GID
            #   value: "1000"
          volumeMounts:
            - name: paperless-data
              mountPath: /usr/src/paperless/data
            - name: paperless-media
              mountPath: /usr/src/paperless/media
            - name: paperless-media
              mountPath: /usr/src/paperless/consume
            - name: paperless-media
              mountPath: /usr/src/paperless/export
      volumes:
        - name: paperless-data
          persistentVolumeClaim:
            claimName: paperless-data
        - name: paperless-media
          persistentVolumeClaim:
            claimName: paperless-media