apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/amrap030/k3s-gitops"
    path: cluster
    targetRevision: HEAD
    plugin:
      name: kustomize-enable-helm
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
