apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: proxmox-redirect
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`proxmox.amrap030.home`)
      kind: Rule
      services:
        - name: proxmox-redirect-service
          port: 8006