apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: proxmox-ingress
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`proxmox.amrap030.home`)
      kind: Rule
      services:
        - name: proxmox-service
          kind: Service
          port: 8006
  tls:
    secretName: traefik-cert