kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: proxmox
  name: proxmox-service
  namespace: default
spec:
  type: ExternalName
  ports:
    - name: proxmox
      port: 8006
      targetPort: 8006
  externalName: 192.168.1.100
  selector:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: traefik