apiVersion: v1
kind: Secret
metadata:
    name: paperless-postgres-secrets
    namespace: paperless
    labels:
        app: postgres
data:
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:bmkHXzH0aT/KqHBH,iv:6kzkTnjo13ulA247fykEVDF2v2EtKNFc8XjMCTbtwLM=,tag:kFiG5hVInsi1kWR7MJ1x3w==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:HNeQMH3qyHzxdyWe,iv:F3I9HIvdsV1mhoofa9z3N1mkrDdzsuhBCQ7qhsMj13s=,tag:mZPaBbYgUGf6FNORthK1uQ==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:HYSUFYK8N3+Ybmk/8NOronKZmoY=,iv:L04Rd1qT90MF3iRA9vQbfUo5dlUka24nFZquOXG7xuY=,tag:H6n0+/cCe68ioK9fGSJstA==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u30r06zu0jacsxj3m33rqggfw49up55jm0cs4hcax0vsrq4nl34s5xpg76
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2eVJFSGI1L3dWL1pxL1A1
            dFVScHpHc3Z3R2VmRHVSSjFaYVo5TUFhRlc0CmpSeUpKZ0t0UWt6ZmhIdFBjQlVs
            NGFXZitGT2JKWFBWUWhtNkRQQnlXd2sKLS0tIEV2VmRPbWlQU1QvU2lBSExRclhp
            enpJU0RZUzNWTHNGZVppanNpeWJNWEkKjvGVTWFa1vLPiUG1O7fLpol9cz+pKNDc
            WFYGA+WG9wT3/1GWsqaVffnKxuwLfwcDOwn2vymC3qn7gA6mvZsg3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-11T11:43:56Z"
    mac: ENC[AES256_GCM,data:7ZvzNuobK5NVhKkUQTU1zUBTn8+ugsD+OLuL4pKE3V4EHNgKRFKrKHMeMJZHfYqdOMohyHSbII5iHiZ8VLYZvKL4H0zKI/PHgER6ODXRcOoaXzxbwQon5eMlDgKpEDUUaB3mgPyNxq2a/T7eIMNoYm49Qa7cpCFXtdzIe8ihJoE=,iv:M8TFkUxRBkHK9OGhzBV+b11EQkB4TBKBv3Ha1Mf1QFs=,tag:W+ARDN9Xh1Aky8bRBrHREA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
