apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
    namespace: kube-prometheus
stringData:
    adminUser: ENC[AES256_GCM,data:U3d16+w=,iv:LXyZCrVp0VGTckqpW+naPe9KgSkjiRUV4Y7hiiK7OOY=,tag:tJDIf1s9Ps9N5YB3y1sbhg==,type:str]
    adminPassword: ENC[AES256_GCM,data:R9vHFCHZiRhJb6T3Lzg=,iv:GBK8HynRQj1IeQtS9GZFtynQlW7S6GPimXBqIukDpNk=,tag:+mucrRfm+bosuiSZCwOIpA==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u30r06zu0jacsxj3m33rqggfw49up55jm0cs4hcax0vsrq4nl34s5xpg76
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDbXJWUExTWXpKTWxITmkw
            RnJ4ZGYvb1E1ME1Tajdpdm1IUHVCQlJScmtVClU1bW5QYy9jTXY2N3JEb2huc3BO
            TG8vUm42YWZJQktDM0tHclFueVJsNHMKLS0tIHRXSFBYMEM1UFliVW5iMzB3VzI5
            QkFLUWFZMlZSQjk4MmM2WEFiMjJLRDAKcd1AHzzgPlt9NNFcdV1RfERRsFOZxM95
            Y5Y29SdHYCTVJdQrcgKzmbx213nZgPxPPiDzqG5eLzGgonnhpxf+3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-11T20:36:24Z"
    mac: ENC[AES256_GCM,data:DwwOtKs8oIK/ftX3rnSRToH9V5u9W1BWgzPEkxTOPRKEq1BOx+vEvKKvlTBzR93T84SHmFKa4X3r7OnjiC8hVWgWUpN0NZhuSldHkhdx7dsVHgH2Bimud28noyw4Kc6O3IOAx2aCsFRzb38qwWor2X1tGCRuyp7N9KRdxAtan4o=,iv:lhY933c2VbtRnW2QbVbVjEOtkB9Yz6lAy0kzUzTF5fI=,tag:cVUMSYYhz8rWwPTmZjgWgg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
