apiVersion: v1
kind: Secret
metadata:
    name: paperless-mariadb-secrets
    namespace: services
    labels:
        app: mariadb
data:
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:H+KgQKsasfUjZCkK,iv:ReXA+hHNYVU921BXkblvXLhuME8/W6qr48K0aALlu1g=,tag:K/hF1t7cMyZ7hBoYVD9pAQ==,type:str]
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:E+YpzpWXkV5jcQWS,iv:/DYEkBPS4zglfh+X7CQIx/d7ZkrCRdUehYXNYoDsXec=,tag:lfKrto3t9HZxyfCqwD/D/g==,type:str]
    MARIADB_PASSWORD: ENC[AES256_GCM,data:aqcRDMy/N/9qOV/v,iv:n1dpfP9ijqgwW5F3RLc336eECZ8LOtfpf6PmxYSC6Cs=,tag:juPLTNNRPHA7OIfBrL9r9g==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:Xd6NUB6HCLMJe/6e,iv:Xs+Oq1F4aFAKMA57y1V1GqHxDTEjMcdD2k2RYr6ix5o=,tag:wEkKt0kv0tQH92txgtZEWA==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u30r06zu0jacsxj3m33rqggfw49up55jm0cs4hcax0vsrq4nl34s5xpg76
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDWmpkbStETTFzTnRIMmZM
            d1ZJRU50YjFuWlVuN2RyL0FpTk9oVGc3UTFRCkx4Y1ZDTlFHcVVPNHpiRDhMNGtu
            SmJVRkQ4dE5TQWpCOU9WaU1EajQ0RVkKLS0tICtRcUEydyt3bG45aTVlOXpQY3VH
            dm5YRk5WVFFqWlVFZ1BCV1hOekFWQkEKLBM5uu2a2vsIn2eX4++Exo8IzEItmOOS
            D1MJqyirfABWDRzg0LBI9kdnF8khTsmcf9B1+sHzC41YOYwFlOLg6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-31T00:40:11Z"
    mac: ENC[AES256_GCM,data:YZKOKFsjH4ZxNx9H4cEWfbk8cu1n2wbfMSZ+ZkzS+vqvDXFS9QOtsM1jzb/rmmVgYGRAUY+Wu01TBenyQs6N+AzO69hxzPSZcW6HyWGnOBaQy1vurAF/Y2dti4hzAl3nETkMux7pZgRGCRDe0EML/nSOOcOtY/5GIaaS7cDOPhI=,iv:fju+LOP8daSUlpSVPxM6NGSNPR3+SBDX87qr4fIZwKU=,tag:d4+K+s1YpCFFOcsSm6wxUw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
