apiVersion: v1
kind: Secret
metadata:
    name: paperless-postgres-secrets
    namespace: services
    labels:
        app: postgres
data:
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:Utaf28iIGgmD9Kxq,iv:LNw6DTtcZuMAQT6LxEEWmnuC/uC3Ev+ySvFJg5xE0M4=,tag:Zlnnd1kEqX5+jwiPdaBrjg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:DYm0slMpHujO2UOY,iv:jfm86+n/HXeYPvEtc1LKCLImCkBGXNuHBmZ40brljeU=,tag:CR1BlFZ49CK53gqABKuzXw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u30r06zu0jacsxj3m33rqggfw49up55jm0cs4hcax0vsrq4nl34s5xpg76
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDWmpkbStETTFzTnRIMmZM
            d1ZJRU50YjFuWlVuN2RyL0FpTk9oVGc3UTFRCkx4Y1ZDTlFHcVVPNHpiRDhMNGtu
            SmJVRkQ4dE5TQWpCOU9WaU1EajQ0RVkKLS0tICtRcUEydyt3bG45aTVlOXpQY3VH
            dm5YRk5WVFFqWlVFZ1BCV1hOekFWQkEKLBM5uu2a2vsIn2eX4++Exo8IzEItmOOS
            D1MJqyirfABWDRzg0LBI9kdnF8khTsmcf9B1+sHzC41YOYwFlOLg6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-27T22:57:29Z"
    mac: ENC[AES256_GCM,data:03BywAa4p036vYLPjAcNQ8dQXRZvhSyY4LTW8JwddzcNnwfKoj2qvf1uLi3UuXX5O9eHHXZeiwo1+Tj36byyotqBhnSpvwTEKKd9nTCKaGIra3kLoN+jpWKZeJmPV+KfLNX1bbOtZoOKCPW99/9uG42LozcxCN5R5v/EkODBMjk=,iv:q6hkQokgfppbcmMiOvSSU9ps00FnUILm+my6L8D6LqI=,tag:ZS/qWlOWcxL1BOvCyCVPhQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
