apiVersion: v1
kind: Secret
metadata:
    name: photoprism-mariadb-secrets
    namespace: services
data:
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:AEbXIzCp5RVzcsZr,iv:oP9Ck/60SK9AbIxAMrOmm0CFbMLW77gyitKZu+sGQGg=,tag:LyWJpg5/vLC/B4xnRDBXuA==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:PL5mPvV5KSUbz5Bl,iv:A8rJdRf0nyJKrWrYeZVySmBS7ivuqeu7n+kIC5TF3Kg=,tag:JEKsJQG22P0zTrRnbadenw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u30r06zu0jacsxj3m33rqggfw49up55jm0cs4hcax0vsrq4nl34s5xpg76
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxV3BJZmRaNUhjOUw1SGlD
            eVNCSTNndnNsaEQ2WEJCVGtHNkxnR25GNzBBCkJEM2l2ZlpWRjZEbzRNT0svSG0x
            Wm9JQTRHZFZURUEyd3BxOUZGRkJBaHMKLS0tIEFzTzFHc2U4UDB2UGlYWHlJaTVZ
            djF2ZjAzTHNWRWFabUdmTlE4dlNqekEK7eqsSlM7m/RTOkq8Tw8Ln7xJivVEng2t
            i3qhrIYH94tobWfsjA+fi3/XkmHf2wzGeymu02V5obSF2Y9EbXRz7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-23T21:11:50Z"
    mac: ENC[AES256_GCM,data:8CAa2R8apmNSzU4oZcAui4TqrreEFfNvKhRzbvP0zP8aIylGVQSXyDlVdoa3CLKTTBKr11tsiiW50c6JtMeNlSqZ19yU22DZbTySexRLAEI9v7wh679q6lsvLVqPElF1Id2FVP+JmCwyNb/10hfU8eGcOkWK/ymCe5lLynDOdls=,iv:Z7fgKu1tHYHxTXoBVwOx1DIDD2jeLNOzwHKNSgUiVQI=,tag:VcbLaMt8o+mFc3PiWcdHTA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
