apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
    namespace: services
data:
    ADMIN_TOKEN: ENC[AES256_GCM,data:4hQFKs6Wqqt0gQRt8IKC8Un3kjtVYeKmOLk3fGfj+74agR5tH/U/v7fQak2RLxA4Ik1vGjpIHrNp5RykSBKMO7VMOGo48bbwZ/HXOAlA4HyxEIpSMF+hPQ==,iv:+ZbPokWO04Qaki/LSroE2ELuGkaoUaoE8FeoGQkCwWw=,tag:8ek885ovTzbAo2ZIS2QBhA==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:ZZANuaer+IS3orWNitQ+rlyWf9tki3Cy,iv:d0mwveDFwq2i6f2cOedOgJCv6ZhvtLBWbaXzKcGjfts=,tag:RdjlDTLULMRKugDHeUj7gQ==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u30r06zu0jacsxj3m33rqggfw49up55jm0cs4hcax0vsrq4nl34s5xpg76
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TmxvaitrWDNMb09BWWJS
            L1pCQlc2U3JzbndWVUJDSTZCcHpkY2FkZDE0CmtoWStLa294aHU5VjR5WE9pWkNp
            d2UvY09ZSUNHbE5IOERyNmNVRzd4SFUKLS0tIGdXZXhvU1BnaGxRRlovZ2x5N2lL
            SHpwL0d6czNTcWNWMzF5RHpUd3loTTgKH6SVeSdqaQuLdEbcMdvUkKvVUJUy6qxr
            hicBmf+NiXZKoLBkx/UHfJsWg0hi/3bVzigWzyOAb1f7QW92/UFw0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-23T14:08:27Z"
    mac: ENC[AES256_GCM,data:In9iXKJGof+Ocdptt+OEjzJ2GESZDLhjWrxIrrwo+FwbFmicCtwYONcSiJaoigfCjPkdykRbR1+z5q0Do2VEUDUg995SGr5LE8+j47/VVdwJOwUlKYxdYnRK6f71FqLdDU1gj+XgRZXYNcoAZdereYAreMBE9igbGTK7gxxYT3M=,iv:imTmiE1VFbHE3/InorihURABEU+Kq8soillZ/VTk0IE=,tag:lzwdswacrBdkhicoOcjEEQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
