kube-prometheus-stack:
  ## Configuration for alertmanager
  ## ref: https://prometheus.io/docs/alerting/alertmanager/
  ##
  alertmanager:
    ## Deploy alertmanager
    ##
    enabled: false

  ## Using default values from https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
  ##
  grafana:
    enabled: true

    admin:
      ## Name of the secret. Can be templated.
      existingSecret: "grafana-secret"
      userKey: adminUser
      passwordKey: adminPassword

    command:
      - "sh"
      - "-c"
      - "grafana-cli admin reset-admin-password ${GF_SECURITY_ADMIN_PASSWORD} && /run.sh"

    persistence:
      enabled: true
      type: pvc
      storageClassName: longhorn
      existingClaim: grafana-data
      finalizers:
        - kubernetes.io/pvc-protection
    
    grafana.ini:
      date_formats:
        default_timezone: UTC
    
    sidecar:
      logLevel: WARN
      dashboards:
        enabled: true
        searchNamespace: ALL
        label: grafana-dashboard
        labelValue: 'true'
        provider:
          foldersFromFilesStructure: true
      datasources:
        enabled: true
        searchNamespace: ALL
        label: grafana_datasource
    
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - type: file
            name: Network
            folder: Network
            editable: true
            allowUiUpdates: true
            disableDeletion: false
            options:
              path: /tmp/dashboards/Network
              foldersFromFilesStructure: true
          - type: file
            name: Cluster
            folder: Cluster
            editable: true
            allowUiUpdates: true
            disableDeletion: false
            options:
              path: /tmp/dashboards/Cluster
              foldersFromFilesStructure: true

  ## Deploy a Prometheus instance
  ##
  prometheus:
    ## Settings affecting prometheusSpec
    ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#prometheusspec
    ##
    prometheusSpec:
      ## Interval between consecutive scrapes.
      ## Defaults to 30s.
      ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/release-0.44/pkg/prometheus/promcfg.go#L180-L183
      ##
      scrapeInterval: "60s"

      ## How long to retain metrics
      ##
      retention: 10d

      ## Maximum size of metrics
      ##
      retentionSize: "8GB"

      ## Prometheus StorageSpec for persistent data
      ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/storage.md
      ##
      storageSpec:
      ## Using PersistentVolumeClaim
      ##
        volumeClaimTemplate:
          metadata:
            name: prometheus-data
          spec:
            storageClassName: longhorn
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 10Gi
          # selector:
          #   matchLabels:
          #     app.kubernetes.io/name: prometheus-metrics
      
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      probeSelectorNilUsesHelmValues: false