vaultwarden:
  image:
    repository: vaultwarden/server
    tag: 1.28.1-alpine
  env:
    DATA_FOLDER: data
  ingress:
    main:
      enabled: false
  persistence:
    data:
      enabled: true
      type: pvc
      accessMode: ReadWriteOnce
      storageClass: longhorn
      size: 10Gi
      mountPath: /data
  postgresql:
    enabled: false
  mariadb:
    enabled: false