vaultwarden:
  image:
    repository: vaultwarden/server
    tag: 1.28.1-alpine
  envFrom:
    - secretRef:
        name: vaultwarden-secret
  env:
    DATA_FOLDER: data
    SIGNUPS_ALLOWED: false
    INVITATIONS_ALLOWED: false
    WEBSOCKET_ENABLED: true
    WEBSOCKET_ADDRESS: 0.0.0.0
    WEBSOCKET_PORT: 3012
    DOMAIN: https://vaultwarden.amrap030.site
    ADMIN_TOKEN: password
    TZ: Europe/Berlin
  ingress:
    main:
      enabled: false
  persistence:
    data:
      enabled: true
      type: pvc
      accessMode: ReadWriteOnce
      storageClass: longhorn
      size: 10Gi
      mountPath: /data
  postgresql:
    enabled: false
  mariadb:
    enabled: false