vaultwarden:
  image:
    repository: vaultwarden/server
    tag: 1.29.2-alpine
  envFrom:
    - secretRef:
        name: vaultwarden-secrets
  env:
    DATA_FOLDER: data
    DOMAIN: https://vaultwarden.amrap030.site
    INVITATIONS_ALLOWED: false
    SIGNUPS_ALLOWED: false
    SMTP_FROM_NAME: Vaultwarden
    SMTP_FROM: kevin.hertwig@gmail.com
    SMTP_HOST: smtp.gmail.com
    SMTP_PORT: 465
    SMTP_SECURITY: "force_tls"
    SMTP_USERNAME: kevin.hertwig@gmail.com
    TZ: Europe/Berlin
    WEBSOCKET_ENABLED: true
    WEBSOCKET_ADDRESS: 0.0.0.0
    WEBSOCKET_PORT: 3012
  ingress:
    main:
      enabled: false
  persistence:
    data:
      enabled: true
      # type: pvc
      # accessMode: ReadWriteOnce
      # storageClass: longhorn
      # size: 10Gi
      existingClaim: "vaultwarden-data"
      mountPath: /data
  postgresql:
    enabled: false
  mariadb:
    enabled: false