apiVersion: v1
kind: Secret
metadata:
  name: traefik-dashboard-auth
  namespace: traefik
type: Opaque
data:
  users: ENC[AES256_GCM,data:nl4Qq39Ys+m7h1t3GRMiY4IEwizel3ac+oCRH+GcFq7u42eP6tyciUoRFOkcZvIg9gy4zF7rl5jz6LHhNLkXxg==,iv:46+twosuU0lAalrx60Ro1KW9stQDkvUNqERjHWaXAa4=,tag:uwc+4ZmLY4vcG1e0GiQg0g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1u30r06zu0jacsxj3m33rqggfw49up55jm0cs4hcax0vsrq4nl34s5xpg76
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUDU2L2Vnc2FlbUpIZnNi
        cldaYXFaUXhOZzdYNDNlcmlPSWFqWkFWY240CnVCcyt3SmRSbXdTQ21SR29hYWFS
        Uis5cnBpWnlxSlB5LzRQL0xzcVBMTVEKLS0tIElYUFVTb001UFd4aW5yS3U2SkhJ
        S1VPY3E0U1RFOW1wNzZPemFENHJ4RDgKSyNQZa07tTGRvyF2NKWgWzCkktPr86oc
        TcPKFCZfFsKPPdMGK3t3mZxvHCoAbZnhOzhONpHqrx5uLdCkdUe0Eg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-06-19T21:44:21Z"
  mac: ENC[AES256_GCM,data:Mwwda3oEQiIodSCwe4hIzslcYIGTDOMZuMthFc/veADEHqmHjWFvYkQOUe+RDAgCAfJvV+1eW8E7BmZOEwvEHm+RHVHWRFd6lQIdNIdpYdFfeg24Kc/jej1Jbx3J0a4EA9RhqTx3VVfYb3zPBhq+gNM3eQqN4CyVa/WiOd+/5Ls=,iv:dmU2mm0UwOo9MC9MJhxWcyUGk/fWN8cGumQiYJ4bOr8=,tag:/QUW3/f+KCS84NQQ37wCcA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
