---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-postgres
  namespace: services
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi