apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml

helmCharts:
  - name: traefik
    repo: https://helm.traefik.io/traefik
    version: v2.10.1
    namespace: traefik
    valuesFile: values.yaml
