apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/traefik/traefik/v2.10/docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml
  - https://raw.githubusercontent.com/traefik/traefik/v2.10/docs/content/reference/dynamic-configuration/kubernetes-crd-rbac.yml
  - default-headers.yaml
  #- secrets.sops.yaml
  - middleware.yaml
  - ingress.yaml

helmCharts:
  - name: traefik
    repo: https://helm.traefik.io/traefik
    version: 23.1.0
    namespace: traefik
    valuesFile: values.yaml
