# Default values for Traefik
traefik:
  image:
    # -- Traefik image host registry
    registry: docker.io
    # -- Traefik image repository
    repository: traefik
    # -- defaults to appVersion
    tag: "v2.10.5"
    # -- Traefik image pull policy
    pullPolicy: IfNotPresent

  #
  # Configure the deployment
  #
  deployment:
    # -- Number of pods of the deployment (only applies when kind == Deployment)
    replicas: 1
    
  ## Create an IngressRoute for the dashboard
  ingressRoute:
    dashboard:
      # -- Create an IngressRoute for the dashboard
      enabled: false
      
  providers:
    kubernetesCRD:
      ingressClass: traefik-external

  # -- Global command arguments to be passed to all traefik's pods
  globalArguments:
    - "--global.checknewversion=false"
    - "--global.sendanonymoususage=false"

  #
  # Configure Traefik static configuration
  # -- Additional arguments to be passed at Traefik's binary
  # All available options available on https://docs.traefik.io/reference/static-configuration/cli/
  ## Use curly braces to pass values: `helm install --set="additionalArguments={--providers.kubernetesingress.ingressclass=traefik-internal,--log.level=DEBUG}"`
  additionalArguments:
    - "--serversTransport.insecureSkipVerify=true"
    - "--log.level=INFO"

  ports:
    web:
      # Added in 2.2, you can make permanent redirects via entrypoints.
      # https://docs.traefik.io/routing/entrypoints/#redirection
      redirectTo: websecure

  service:
    spec:
      loadBalancerIP: "192.168.1.180"