apiVersion: v1
kind: Secret
metadata:
    name: photoprism-secret
    namespace: photoprism
data:
    PHOTOPRISM_ADMIN_PASSWORD: ENC[AES256_GCM,data:dwWhDoc17bzeCGlB,iv:0+EyluBvpg6QR5CIA8t+DDnga8czJXiBwzTdMCehkkk=,tag:1WmZI0m73u+q2Vf+dFsIBQ==,type:str]
    PHOTOPRISM_DATABASE_PASSWORD: ENC[AES256_GCM,data:dBNuP3E0Vva1HkzU,iv:uqLmLVlRrVXpBgquqvp75yYaiWD2lZHj4Sl1HPte274=,tag:9UVXwdaL5+J/QVl1o7blFA==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u30r06zu0jacsxj3m33rqggfw49up55jm0cs4hcax0vsrq4nl34s5xpg76
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcTNieFJteE43N1o3b2w1
            Mk03V2tmQmZPckhIb1BUbFZJMFlYR1RoN0NjCnprb25uLzU2ei9aNTJwcDZQeHUr
            N3YxNHh4ajkyN2lWNkdYOGx5aGE4VTAKLS0tIDJiZ1RHSHFDUWhGdGhXaUprYXNV
            ODIzOVdRRXFNb0dCc1EvdWVQZTh6VTAK1BJS62SPJrP7WYS17vbOpYy3ba9oCOrw
            8iyZQ4baHSR5oru+Ur+cDl4P1Q2n804Q/clW+OKeQtIMsRwZ3ZngMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-11T12:14:07Z"
    mac: ENC[AES256_GCM,data:Lz8it+XSfJ2xjSPps5Hm/Fz2YnxSvWGPl/QOMadlG1hFCqhhonYSwcRoRoBSEQGvSDZP7ydiC0DxOagKu1IV4QWf0SkZkyo0o+2+LiOkzgFBbKU9hNtT1h7WYm/J/ma6KaNUDH6MRgQf/PBA18jMah3Hp96ka3/nA4lUdxtq31Q=,iv:zFTv7xVhVt/RSmEKiFpP/gp0Hh/kPP5FsfxaME/4Bgk=,tag:BNVLYW2g3B1bAPKl40LY0g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
