apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server
  namespace: services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-server
  template:
    metadata:
      labels:
        app: redis-server
        name: redis-server
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
          args:
            - "redis-server"