apiVersion: v1
kind: Secret
metadata:
    name: unifi-poller-secrets
    namespace: unifi-poller
    labels:
        app: unifi-poller
        type: poller
stringData:
    UP_POLLER_DEBUG: ENC[AES256_GCM,data:l2Zoidw=,iv:D8dmZDLv8exae6SK4xui+UoL4xc0fTznfs93jabh7+U=,tag:TaEYj/4325lsxYy8JqZm/A==,type:str]
    UP_POLLER_QUIET: ENC[AES256_GCM,data:9KFquw==,iv:XAkdjUpcLiJUH3C0y2TbsAxhpHMd3H0EXel7x6nEf1E=,tag:ZlxYfqlGbC4SuHMcfJfglA==,type:str]
    UP_UNIFI_DYNAMIC: ENC[AES256_GCM,data:abFO32U=,iv:RPuts7+zBsSlJtzAmdwmT3SoaogfMEC6dzeBh5Bnt94=,tag:PqR98eWfl9kRhp22U3Iisw==,type:str]
    UP_UNIFI_DEFAULT_URL: ENC[AES256_GCM,data:vA1NpkEqYZdj8uYYqmq056HyQg75V1/B,iv:4u/G4nNLaOdF/676q4EnjMbjhBBViXNEghIRpkxSvFA=,tag:zxT4n3cWpo8CYLq/z25/vQ==,type:str]
    UP_UNIFI_DEFAULT_USER: ENC[AES256_GCM,data:5HuTikubq9A=,iv:RdA4CWMV9NHNLfe4Ov45BlIUg39FkdsfP5D+BTHirRk=,tag:jTdx8OspRQE2pUhz8xrjGQ==,type:str]
    UP_UNIFI_DEFAULT_PASS: ENC[AES256_GCM,data:AyUi0X31PzlzHd1jSms=,iv:d9YcEnoKUoI1M7pjUPDMF0Csw5v63NlL59hzCRCVG/c=,tag:xOJSrmcrG870v4aV53PsUg==,type:str]
    UP_INFLUXDB_DISABLE: ENC[AES256_GCM,data:WbRJmg==,iv:aT+V5bkZ04E8xbCxlPQgNt7j6iTNWsrbH0yqmOejoFw=,tag:c5wYrU12HQH7tM9mcmWlnw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u30r06zu0jacsxj3m33rqggfw49up55jm0cs4hcax0vsrq4nl34s5xpg76
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHOXdMK21uZEcwWWFuQlN3
            Tzk0aXc4R3llZVhIUE9pZWdQdnMyT0ZiK2hjCmYzbFVIL21FRmYwWUl2cEVxUHZP
            SE9KYndYdm5qV2I4d24zU2R3V3JDZG8KLS0tIEtubTY4eVpCWWxiSnJvb3ptL0Z5
            RWdMdzNhdlcrSDNVL0svNGp5ZTI2SEUK8ZMLon5ibDZ8Nn0HTKuCWnnEMbf2UxTW
            zVHLLodL4llve+izNtOYcNupdFf4Oe0y/w1FwuU96SEbJG8Sc1nhvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-14T19:39:40Z"
    mac: ENC[AES256_GCM,data:tqE6+332LPAsJmRZLE9fqJhb800Yr+w8yY+squ//7LRshIsqCSEjCYaZuIMCM0+5FOLp/sYBvwb7OKVhE10aM4rpZkEEngC86dzKIgYOS6lmP/X+bVty9r58IpBd0SVHxKfYDLJaEogD0SEtt048XZ5wUV2U40DCz+1D4u0l6vY=,iv:Txj0LCZ+D4wF79ygQWwM2GnVa8pu4Qw9l4cTM4HOedo=,tag:6LDu+HMhzBzUM1g4nmQSgg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
