cert-manager:
  installCRDs: true

  image:
    repository: quay.io/jetstack/cert-manager-controller
    # You can manage a registry with
    # registry: quay.io
    # repository: jetstack/cert-manager-controller

    # Override the image tag to deploy by setting this variable.
    # If no value is set, the chart's appVersion will be used.
    tag: "v1.13.1"

    # Setting a digest will override any tag
    # digest: sha256:0e072dddd1f7f8fc8909a2ca6f65e76c5f0d2fcfb8be47935ae3457e8bbceb20
    pullPolicy: IfNotPresent

  webhook:
    image:
      repository: quay.io/jetstack/cert-manager-webhook
      # You can manage a registry with
      # registry: quay.io
      # repository: jetstack/cert-manager-webhook

      # Override the image tag to deploy by setting this variable.
      # If no value is set, the chart's appVersion will be used.
      tag: "v1.13.1"

      # Setting a digest will override any tag
      # digest: sha256:0e072dddd1f7f8fc8909a2ca6f65e76c5f0d2fcfb8be47935ae3457e8bbceb20

      pullPolicy: IfNotPresent

  cainjector:
    image:
      repository: quay.io/jetstack/cert-manager-cainjector
      # You can manage a registry with
      # registry: quay.io
      # repository: jetstack/cert-manager-cainjector

      # Override the image tag to deploy by setting this variable.
      # If no value is set, the chart's appVersion will be used.
      tag: "v1.13.1"

      # Setting a digest will override any tag
      # digest: sha256:0e072dddd1f7f8fc8909a2ca6f65e76c5f0d2fcfb8be47935ae3457e8bbceb20

      pullPolicy: IfNotPresent

  acmesolver:
    image:
      repository: quay.io/jetstack/cert-manager-acmesolver
      # You can manage a registry with
      # registry: quay.io
      # repository: jetstack/cert-manager-acmesolver

      # Override the image tag to deploy by setting this variable.
      # If no value is set, the chart's appVersion will be used.
      tag: "v1.13.1"

      # Setting a digest will override any tag
      # digest: sha256:0e072dddd1f7f8fc8909a2ca6f65e76c5f0d2fcfb8be47935ae3457e8bbceb20

  # This startupapicheck is a Helm post-install hook that waits for the webhook
  # endpoints to become available.
  # The check is implemented using a Kubernetes Job- if you are injecting mesh
  # sidecar proxies into cert-manager pods, you probably want to ensure that they
  # are not injected into this Job's pod. Otherwise the installation may time out
  # due to the Job never being completed because the sidecar proxy does not exit.
  # See https://github.com/cert-manager/cert-manager/pull/4414 for context.
  startupapicheck:
    image:
      repository: quay.io/jetstack/cert-manager-ctl
      # You can manage a registry with
      # registry: quay.io
      # repository: jetstack/cert-manager-ctl

      # Override the image tag to deploy by setting this variable.
      # If no value is set, the chart's appVersion will be used.
      tag: "v1.13.1"

      # Setting a digest will override any tag
      # digest: sha256:0e072dddd1f7f8fc8909a2ca6f65e76c5f0d2fcfb8be47935ae3457e8bbceb20

      pullPolicy: IfNotPresent