
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: photoprism
    app.kubernetes.io/name: photoprism
  annotations:
    volume.beta.kubernetes.io/storage-class: "truenas-nfs"
    argocd.argoproj.io/sync-options: Delete=false
  name: photoprism-originals
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1024Gi
  storageClassName: truenas-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: photoprism
    app.kubernetes.io/name: photoprism
  annotations:
    volume.beta.kubernetes.io/storage-class: "truenas-nfs"
    argocd.argoproj.io/sync-options: Delete=false
  name: photoprism-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: truenas-nfs